config/routes.rb
Rails.application.routes.draw do
  resources :channels, except: :show do
    collection do
      get :upload_csv
      post :upload_csv
    end
    member do
      put :update_videos
    end
  end
  resources :videos, except: :show
  get '/notify', to: 'application#notify'
  post '/notify', to: 'application#notify'

  devise_for :users, :controllers => { :sessions => 'sessions' }

  root :to => 'channels#index'

  namespace 'api' do
    resources :channels, only: :index
    resources :videos, only: :index
  end
end

app/models/channel.rb
require 'csv'

class Channel < ApplicationRecord
  include YoutubeSyncable

  has_many :videos, dependent: :destroy
  validates :name, length: { minimum: 3 }, presence: true
  validates :youtube_id, length: { minimum: 5 }, presence: true, uniqueness: true
  validate :youtube_id_is_valid_on_youtube

  translates :name
  globalize_accessors

  def self.import_csv(csv_text)
    csv = CSV.parse(csv_text, :headers => true)
    channels = []
    csv.each do |unstriped_row|
      row = {}
      unstriped_row.each{|k, v| row[k.strip] = v.strip}
      channel = Channel.create(row.to_hash)
      
      unless Rails.env.test?
        yt_channel = Yt::Channel.new(id: channel.youtube_id)
        if yt_channel.present? && yt_channel.thumbnail_url.present?
          channel.icon = yt_channel.thumbnail_url
          channel.save!
        end
      end
      
      channels << channel
    end
    channels
  end

  def update_videos
    add_videos
    delete_videos_missing_from_yt
  end
  
  def add_videos
    new_videos.each do |video|
      new_video = Video.new(video)
      new_video.channel_id = id
      new_video.save
    end
  end
  
  def new_videos
    if videos.count == 0
      yt_videos
    else
      videos_in_origin = yt_videos
      new_ids = videos_in_origin.map {|x| x[:youtube_id]} - videos.map {|x| x.youtube_id}
      result = []
      videos_in_origin.each do |video_in_origin|
        if new_ids.include? video_in_origin[:youtube_id]
          result.push(video_in_origin)
        end
      end
      result
    end
  end
  
  def videos_count
    videos.count
  end
  
  def update_icon
    self.icon = yt_icon
  end
end

app/controllers/api/channels_controller.rb
class Api::ChannelsController < Api::BaseController
  load_and_authorize_resource
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  load_and_authorize_resource
  before_action :update_icon, only: [:create, :update]

  def create
    if @channel.save
      redirect_to channels_url, notice: 'Channel was successfully created.'
    else
      render_with_alert :new
    end
  end

  def update
    if @channel.update(channel_params)
      redirect_to channels_url, notice: 'Channel was successfully updated.'
    else
      render_with_alert :edit
    end
  end

  def update_videos
    @channel.update_videos
    redirect_to videos_url, notice: 'The videos list was successfully updated.'
  end

  def upload_csv
    if request.post?
      csv_text = params[:csv_file].read
      @channels = Channel.import_csv(csv_text)
      redirect_to channels_url, notice: 'The Channels list was successfully updated.'
    end
  end

  def destroy
    @channel.destroy
    redirect_to channels_url, notice: 'Channel was successfully destroyed.'
  end

  private
  def channel_params
    params.require(:channel).permit(:name_en, :name_ar, :youtube_id, :icon)
  end

  def render_with_alert(template)
    flash[:alert] = @channel.errors.full_messages.to_sentence
    render template
  end

  def update_icon
    @channel.update_icon
  end
end

app/views/channels/_form.html.erb
<%= simple_form_for(channel) do |f| %>

  <%= f.input :name_en %>
  <%= f.input :name_ar %>
  <%= f.input :youtube_id %>

  <%= f.submit :class => "btn btn-primary" %>
<% end %>

app/views/channels/edit.html.erb
<%= flash_messages %>
<h1>Editing Channel</h1>

<%= render 'form', channel: @channel %><br>

<%= link_to 'Update Channel\'s videos', update_videos_channel_path(@channel), method: :put , class: "btn btn-success"%><br><br>

<%= link_to 'Delete Channel', @channel, class: "btn btn-danger", method: :delete, data: { confirm: "Are you sure you want to delete this channel?" } %>

app/views/channels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Channels</h1>
<%= link_to 'New Channel', new_channel_path , class: "btn btn-default" %>
<%= link_to 'Upload CSV', upload_csv_channels_path, class: "btn btn-success" %>

<table class="table">
  <thead>
    <tr>
      <th>Name (en)</th>
      <th>Name (ar)</th>
      <th>Youtube ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @channels.each do |channel| %>
      <tr>
        <td><%= link_to channel.name_en, edit_channel_path(channel) %></td>
        <td><%= channel.name_ar %></td>
        <td><%= channel.youtube_id %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/channels/new.html.erb
<%= flash_messages %>
<h1>New Channel</h1>

<%= render 'form', channel: @channel %>

app/views/channels/upload_csv.html.erb
<%= simple_form_for :channel, url: upload_csv_channels_path, method: :post, html: {multipart: true} do |f| %>

  <div class="form-group">
    <p class="help">Add a CSV File</p>
    <%= file_field_tag 'csv_file', class: "form-input" %>
  </div>

  <%= f.submit "Upload", :class => "btn btn-primary" %>
<% end %>