config/routes.rb
Rails.application.routes.draw do
  resources :channels, except: :show do
    collection do
      get :upload_csv
      post :upload_csv
    end
    member do
      put :update_videos
    end
  end
  resources :videos, except: :show
  get '/notify', to: 'application#notify'
  post '/notify', to: 'application#notify'

  devise_for :users, :controllers => { :sessions => 'sessions' }

  root :to => 'channels#index'

  namespace 'api' do
    resources :channels, only: :index
    resources :videos, only: :index
  end
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :channel

  validates :name, length: { minimum: 3 }, presence: true
  validates :youtube_id, length: { minimum: 5 }, presence: true, uniqueness: true
  validates :channel, presence: true

  scope :trending, -> { where("videos.created_at >= ?", Time.now-7.days) }
  scope :not_trending, -> { where("videos.created_at < ?", Time.now-7.days) }

  translates :name
  globalize_accessors
end

app/controllers/api/videos_controller.rb
class Api::VideosController < Api::BaseController
  load_and_authorize_resource

  before_action :find_included_youtube_ids, :find_excluded_youtube_ids,:find_page!, :find_page_size, :find_channel_ids!, :find_trending

  def index
    #all
    @videos = Video.where(:hidden => false)
    #trending
    @videos = params[:trending] == "true" ? @videos.trending : @videos.not_trending

    #by channel
    @videos = @videos.where(:channel_id => @channel_ids) if params[:channel_ids]
    # excluded
    @videos = @videos.where.not(:youtube_id => @excluded_youtube_ids) if params[:excluded_youtube_ids]

    # included
    @videos = @videos.or(Video.where(:youtube_id =>  @included_youtube_ids)) if params[:included_youtube_ids]

    # search
    @videos = @videos.where(' lower(video_translations.name) LIKE ?', "%#{params[:q].downcase}%") if params[:q]

    # sort and paginate
    @videos =  @videos.with_translations.order(:created_at).page(@page).per(@page_size)
  end

  private
  def find_included_youtube_ids
      if params[:included_youtube_ids]
        @included_youtube_ids = params[:included_youtube_ids].split(",")
      end
  end

  def find_excluded_youtube_ids
    if params[:excluded_youtube_ids]
      @excluded_youtube_ids = params[:excluded_youtube_ids].split(",")
    end
  end

  def find_page!
    raise ActionController::ParameterMissing.new(:page) unless params[:page]
    @page = params[:page]
  end

  def find_page_size
    @page_size = params[:page_size] || 50
  end

  def find_channel_ids!
    raise ActionController::ParameterMissing.new(:page) unless params[:channel_ids]
    @channel_ids = params[:channel_ids].split(",")
  end

  def find_trending
    if params[:trending] == "true" || params[:trending] == "false"
      @trending = params[:trending]
    end
  end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  load_and_authorize_resource

  def create
    @video.save ? redirect_to(videos_path, notice: 'Video was successfully created.') : render(:new)
  end

  def update
    @video.update(video_params) ? redirect_to(videos_path, notice: 'Video was successfully updated.') : render(:edit)
  end

  def destroy
    @video.destroy
    redirect_to videos_path, notice: 'Video was successfully deleted.'
  end

  private
    def video_params
      params.require(:video).permit(:name_en, :name_ar, :youtube_id, :channel_id, :hidden)
    end

    def multiple_video_params(video_params)
      video_params.permit(:name, :youtube_id, :channel_id)
    end
end

app/views/videos/_form.html.erb
<%= simple_form_for(video) do |f| %>

  <%= f.input :name_en %>
  <%= f.input :name_ar %>
  <%= f.input :youtube_id %>
  <%= f.association :channel %>
  <%= label_tag(:hidden, "Mark if the video should be hidden from the App") %>
  <%= f.input :hidden %>
  <br>

  <%= f.submit :class => "btn btn-primary" %>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form', video: @video %><br>

<%= link_to 'Delete Video', @video, class: "btn btn-danger", method: :delete, data: { confirm: "Are you sure you want to delete this video?" } %>

app/views/videos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Videos</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name (en)</th>
      <th>Name (ar)</th>
      <th>Available</th>
      <th>Youtube ID</th>
      <th>Channel</th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= link_to video.name_en, edit_video_path(video) %></td>
        <td><%= video.name_ar %></td>
        <%if video.hidden%>
          <td><span class="glyphicon glyphicon-remove" aria-hidden="true"></td>
        <%else%>
          <td><span class="glyphicon glyphicon-ok" aria-hidden="true"></td>
        <% end %>
        <td><%= video.youtube_id %></td>
        <td><%= video.channel.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/videos/multiple_new.html.erb
<%= flash_messages %>

<%= simple_form_for :videos, url: create_multiple_videos_path do |f| %>

  <table class="table">
    <thead>
      <tr>
        <th>Row</th>
        <th>Name</th>
        <th>YouTube ID</th>
        <th>Category</th>
      </tr>
    </thead>
  <% @videos.each do |video| %>
  
    <%= simple_fields_for "videos[#{@videos.index(video)}]", video do |g| %>
      <tr class="<%= g.object.valid? ? "" : "danger" %>">
        <td><%= @videos.index(g.object) + 1 %></td>
        <td><%= g.input :name, label: false %></td>
        <td><%= g.input :youtube_id, label: false %></td>
        <td><%= g.association :category, label: false %></td>
      </tr>
    <% end %>
  
  <% end %>
  </table>
  
  <%= f.submit class: "btn btn-default" %>

<% end %>

app/views/videos/new.html.erb
<h1>New Video</h1>

<%= render 'form', video: @video %>

app/views/videos/upload_csv.html.erb
<%= simple_form_for :video, url: upload_csv_videos_path, method: :post, html: {multipart: true} do |f| %>

  <div class="form-group">
    <p class="help">Add a CSV File</p>
    <%= file_field_tag 'csv_file', class: "form-input" %>
  </div>

  <%= f.submit "Upload", :class => "btn btn-primary" %> 
<% end %>