config/routes.rb
Rails.application.routes.draw do
  resources :channels, except: :show do
    collection do
      get :upload_csv
      post :upload_csv
    end
    member do
      put :update_videos
    end
  end
  resources :videos, except: :show
  get '/notify', to: 'application#notify'
  post '/notify', to: 'application#notify'

  devise_for :users, :controllers => { :sessions => 'sessions' }

  root :to => 'channels#index'

  namespace 'api' do
    resources :channels, only: :index
    resources :videos, only: :index
  end
end

app/views/shared/_navbar.html.erb
<div class="navbar" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<%= channels_path %>">
              <div class="title">STC YouTube Kids</div>
          </a>

        </div>
        <div id="navbar" class="navbar-collapse collapse" aria-expanded="true">
          <ul class="nav navbar-nav navbar-right">
              <button type="button" class="navbar-right-expand-toggle pull-right visible-xs">
                  <i class="fa fa-times icon"></i>
              </button>
              <li><%= link_to "Videos", videos_path %></li>
              <li><%= link_to "Channels", channels_path %></li>
              <li><%= link_to "Send Notification", notify_path %></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </div>
    </div>
</div>